### ISSUE TITLE
Add an approach parameter to the location object

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1304]
## Context
Used to indicate how requested routes consider from which side of the road to approach a location. Accepts `unrestricted` (default) or `curb` . If set to `unrestricted` , the routes can approach locations from either side of the road. If set to `curb` , the route will be returned so that on arrival, the location will be found on the side that corresponds with the `driving_side` of the region in which the returned route is located. Note that the `approach` parameter influences how you arrive at a location, while `heading` influences how you start from a location. 

## Task
- [ ] Decide on the parameter name
- [ ] Add logic to parse parameter
- [ ] Add logic to influence the route path
- [ ] Add tests to verify functionality
