### ISSUE TITLE
Identify refs in maneuver street names and exit sign elements

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1310]
## Context
Currently, refs and names are stored together for street names and exit signs. Therefore, a user can not distinguish between refs and names. Do we have to consider other tag items such as language?

## Tasks
Update so a user can distinguish between refs and names while not impacting the current route guidance.

- [ ] Design how to implement
- [ ] Update data
- [ ] Update TripPathBuilder assignments
- [ ] Update pbf as needed
- [ ] Update maneuver and narrative builders
