### ISSUE TITLE
Review and update maneuver types

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1346]
## Context
There has been discussions about adding/updating the current set of maneuver types. We should should review and decide how to proceed 

## Tasks
- [ ] Review current maneuver types
- [ ] Split roundabout types to have direction - [current ticket](https://github.com/valhalla/valhalla/issues/142)
- [ ] Do we need `merge` with relative direction?
- [ ] When decisions are made - add tickets for specific updates
