### ISSUE TITLE
Implement new request interface

### ISSUE THREAD

**Issue by karenzshea** [valhalla/valhalla#1379]
We've designed a draft of the new request and response interfaces. @chaupow is already at work implementing the new version of the response format in https://github.com/valhalla/valhalla/pull/1354. This issue tracks work towards implementing the new request interface as well.

### Tasks
- [x] Finish refactor of parsing requests into pbf https://github.com/valhalla/valhalla/pull/1369
- [ ] Write node bindings https://github.com/valhalla/valhalla/pull/1341
- [ ] Implement request interface design (PR needed)
