### ISSUE TITLE
Review intersecting forward edge logic

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1552]
## Issue
Some deltas were found while testing #1547 - as follows:
``` diff
# duane#30
< 3: Bear right onto Nichols Avenue/CT 108. Continue on CT 108. | 4.2 mi
---
> 3: Bear right onto Nichols Avenue/CT 108. Continue on CT 108. | 2.5 mi

<    VERBAL_POST: Continue on Connecticut 1 o8 for 4.2 miles.
---
>    VERBAL_POST: Continue on Connecticut 1 o8 for 2.5 miles.

< 4: Turn right to take the CT 15 South ramp toward New York City. | 0.2 mi
---
> 4: Bear left onto Huntington Turnpike/CT 108. | 1.7 mi
>    VERBAL_ALERT: Bear left onto Huntington Turnpike.
>    VERBAL_PRE: Bear left onto Huntington Turnpike, Connecticut 1 o8.
>    VERBAL_POST: Continue for 1.7 miles.
> ----------------------------------------------
> 5: Turn right to take the CT 15 South ramp toward New York City. | 0.2 mi
```

``` diff
# demo#2
< 16: Merge onto NY 27. | 6.1 mi
---
> 16: Merge onto NY 27. | 3.5 mi

<    VERBAL_POST: Continue for 6.1 miles.
---
>    VERBAL_POST: Continue for 3.5 miles.

< 17: Turn left onto Nostrand Avenue. | 0.2 mi
---
> 17: Bear left onto Linden Boulevard/NY 27. | 2.7 mi
>    VERBAL_ALERT: Bear left onto Linden Boulevard.
>    VERBAL_PRE: Bear left onto Linden Boulevard, New York 27.
>    VERBAL_POST: Continue for 2.7 miles.
> ----------------------------------------------
> 18: Turn left onto Nostrand Avenue. | 0.2 mi
```
## Tasks

- [ ] Analyze the deltas and forward intersecting edge logic
- [ ] Determine if modification is needed
- [ ] Perform update and test or create a ticket if more details are needed
