### ISSUE TITLE
Update sign info assignment logic

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1661]
## Issue

We added logic to only keep exit sign information on the first edge of a way. Since some data tagging has changed in OSM - we need to revert that logic. Thus, we will assign sign information on each edge of the way. Some recent logic added to `Odin` should be able to handle this update - testing is needed to verify.

```
Test route request:
-j '{"locations":[{"lat":40.227131,"lon":-76.719429,"street":"Vine Street"},{"lat":40.225224,"lon":-76.722420,"street":"PA 283 West"}],"costing":"auto","directions_options":{"units":"miles"}}'
```
``` DIFF
< CURRENTLY
< Turn left to take the PA 283 West ramp.
> SHOULD BE
> Turn left to take the PA 283 West ramp toward Harrisburg/Harrisburg International Airport.
```

## Tasks

- [ ] Update the sign assignment logic in the data producer
- [ ] Create data
- [ ] Test with example route provided
- [ ] RAD test to verify positive changes
