### ISSUE TITLE
Fix merge directional for OSRM Compatibility mode [1]

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1730]
## Issue
Currently, the merge directional is missing when using the OSRM compatibility mode

#### Step 2 and 3

Step 2 banner primary modifier: `slight left` vs. `straight`
Step 3 merge directional: `left` vs. `no directional`
![Merge point](https://d2mxuefqeaa7sj.cloudfront.net/s_CAE9C89108A727D2FC8FC99027C1CEA3978660C1285FE1447AF88267403C6467_1551296361476_image.png)

![banner primary-modifier and Merge directional](https://d2mxuefqeaa7sj.cloudfront.net/s_CAE9C89108A727D2FC8FC99027C1CEA3978660C1285FE1447AF88267403C6467_1551296265307_image.png)

#### Step 2 and 3

Step 2 banner primary modifier: `slight left` vs. `slight right`
Step 3 merge directional: `slight left` vs. `slight right`

![](https://d2mxuefqeaa7sj.cloudfront.net/s_CAE9C89108A727D2FC8FC99027C1CEA3978660C1285FE1447AF88267403C6467_1551301445891_image.png)

![](https://d2mxuefqeaa7sj.cloudfront.net/s_CAE9C89108A727D2FC8FC99027C1CEA3978660C1285FE1447AF88267403C6467_1551301397193_image.png)

## Tasks

- [x] Add logic to assign the merge directional value which will be reflected in the banner primary modifier. The logic must use the relationship of the edges at the intersection and not just the turn degrees.
- [x] Verify merge directional
- [x] Verify banner modifier
