### ISSUE TITLE
Create and use constant values for turn degree values

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1739]
## Issue
Currently, there are many magic numbers that need to be replaced with constant values for turn degree boundaries

## Tasks

- [ ] Create turn degree constant values
- [ ] Use the constant throughout code
- [ ] Test to verify
