### ISSUE TITLE
Collapse extraneous bridge instruction

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1744]
## Issue
In Germany, it is common to name bridges differently then the inbound and outbound roads.
Example:
```{"locations":[{"lat":52.460304,"lon":13.436120,"street":"Jahnstraße"},{"lat":52.456024,"lon":13.438210,"street":"Franz-Körner-Straße"}],"costing":"auto","directions_options":{"units":"kilometers"}}```
![image](https://user-images.githubusercontent.com/7515853/54613255-c4abf480-4a30-11e9-8e26-acdd9e9bdc70.png)

## Tasks

- [ ] Create more tests
- [ ] Add logic to collapse extraneous bridge maneuvers
- [ ] Verify with tests

**Comment by dnesbitt61** [comment]
Long, significant bridges may warrant their own maneuver.

Otherwise I like the idea of "just in time"guidance in conjunction with trace_attributes to make bridge names available. It may be useful to identify these "Crossing Norman Wood Bridge" or something similar to give additional information and validation to the route.
