### ISSUE TITLE
Improve walkway directions within city parks

### ISSUE THREAD

**Issue by dgearhart** [valhalla/valhalla#1761]
## Issue
Currently, the walkway directions within city parks can be improved at the following decision points:

- forks
- differentiating similar turn angles
- circles

Example routes from [pedestrian_routes.txt](https://github.com/valhalla/valhalla/blob/master/test_requests/pedestrian_routes.txt)
routes 5 & 6: forks, turns, relative direction
![image](https://user-images.githubusercontent.com/7515853/55726348-95f4be80-59dd-11e9-9279-af3481b9b5e5.png)

routes 7 & 8 : circles
![image](https://user-images.githubusercontent.com/7515853/55726512-f552ce80-59dd-11e9-8982-c633d5d4c955.png)

## Tasks

- [ ] Analyze each issue
- [ ] Implement solution to improve
- [ ] Test to verify
